### ISSUE TITLE
Could you add a setting to choose a stop header size to the indexer?

### ISSUE THREAD

**Issue by DevonDekhran** [LoyalPotato/potato-indexer#12]
What I mean by this is that the indexer generates links for every header, which would be fine. 

Though in my use-case it would be much more legible and useful if I could limit the indexer to only link headers from H1 to H4, since the I often use smaller headers like H5 and H6 for legibility on the note and have to manually erase them from the generated index.

Not sure if this is where I should write this suggestion, but thank you for the tool regardless!!

**Comment by LoyalPotato** [comment]
That sounds like a great idea!
I'll look into it :) 

Thank you for the suggestion

**Comment by LoyalPotato** [comment]
@DevonDekhran should be in the latest release :)
Let me know if it works out!

**Comment by DevonDekhran** [comment]
You are a god!!!
Was able to try it today and it fits perfectly.
Thank you so much for this!

**Comment by LoyalPotato** [comment]
Glad to see that 😄 
Thank you for your suggestion!
