### ISSUE TITLE
difference between table of contents and index

### ISSUE THREAD

**Issue by ksdavidc** [LoyalPotato/potato-indexer#18]
Unless I am deceived, you are generating a table of contents, not an index.
A table of contents is a sequential list of all the **headings** in a document.
An index is a list of all the significant **words** in a document cross-referenced to their position in the document.

This is confusing, as these are entirely separate things.

**Comment by LoyalPotato** [comment]
You are correct :)

What do you intend with this comment?

**Comment by ksdavidc** [comment]
I was suggesting that instead of using the word index or content index in the readme, you use the words table of contents, so that people will not be misled, as I was, to think that this project does something different than it does.

**Comment by LoyalPotato** [comment]
@ksdavidc I see, sorry about that. I took it as having to rename the whole extension and I wasn't seeing how that was possible.

I've updated the readme.

**Comment by ksdavidc** [comment]
I see. Thanks. There are ways to rename extensions (many of them are doing it now because of new extension guidelines), and I think it has to do with the main json file, but you'd have to look at the obsidian plugin docs for that.

**Comment by ksdavidc** [comment]
I am not saying you have to, just a point of reference. I know it is a work in progress, so hang in there! :-)
